### ISSUE TITLE
How to add IAM role to instance & what are the policy we need.

### ISSUE THREAD

**Issue by Hareeshyalamasetty** [tendai-lino/easyrsa-automation#1]
How to add IAM role to instance & what are the policy we need.

**Comment by tendai-lino** [comment]
Hello

Thank you for reaching out.

Below are the steps:

Step1 : Under IAM go to Roles -> Create Role -> Select AWS Service -> EC2 -> Next:Permissions----> Under create policy search for AWSCertificateManagerFullAccess  and select it--->Next;Tags---->Next:Review and provide Role Name. Then Create.

Step 2 : attach role to instance

Select instance in AWS Console ----->Actions----->Instance settings-------->Attach/Replace IAM role------> Select your newly created Rolecunder drown arrow and Select Apply .

Let me know if my explanation is clear.

Best Regards

Tendai
